---
title: "Seq QC table for manuscript"
author: "Ryan Corbett"
date: "2025"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
params:
  release: v15
---

This script adds the `rna-dna-qt-stats.tsv` data file as a supplemental table for the OpenPedCan manuscript. 

Load packages

```{r setup, include=FALSE}
library(tidyverse)
library(openxlsx)
```

This Rmarkdown generates tables used in the manuscript, including both main text and supplementary material. 

```{r define directories and result files}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
working_dir <- file.path(root_dir, "tables")
# Define data_dir based on ci. The `testing` param covers if we are in CI where 1 is CI.
if (params$release == "testing") {
  data_dir <- file.path(root_dir, "data")
} else {
  data_dir <- file.path(root_dir, "data", params$release)
}
results_dir <- file.path(working_dir, "results")
if(!dir.exists(results_dir)){
  dir.create(results_dir, recursive=TRUE)
}
```

Wrangle data

```{r load data}
qc_df <- read_tsv(file.path(data_dir,
                            "rna-dna-qc-stats.tsv"))
```

Write to `results/`

```{r save}
write.xlsx(qc_df,
           file.path(results_dir, "SuppTable4-dna-rna-qc.xlsx"), 
           overwrite=TRUE, 
           keepNA=TRUE)
```