---
title: "packages for OpenPedCan"
author: "zzgeng"
date: "2024-05-30"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(openxlsx)
```

## generate `software/packages` table
### R packages
```{r}
# Sheet 1: R packages in Docker image
r_packages <- data.frame(installed.packages()[, c(1,3)]) %>%
  rename(`R Package` = "Package")

r_packages
```

### python packages
```{r}
# sheet 2: Python libraries in docker image
python_libraries <- tribble(
  ~Software, ~Version, 
  "Python", "3.11.0",
  "appdirs", "1.4.4",
    "attrs", "23.1.0",
    "certifi", "2023.5.7",
    "chardet", "5.1.0",
    "ConfigArgParse", "1.7",
    "CrossMap", "0.6.5",
    "Cython", "0.29.15",
    "defusedxml", "0.7.1",
    "docutils", "0.20",
    "gitdb", "4.0.10",
    "GitPython", "3.1.31",
    "idna", "3.4",
    "importlib-metadata", "6.6.0",
    "ipykernel", "6.23.0",
    "ipython", "8.13.2",
    "ipython-genutils", "0.2.0",
    "jsonschema", "4.17.3",
    "jupyter-client", "8.2.0",
    "jupyter-core", "5.3.0",
    "MarkupSafe", "2.1.2",
    "matplotlib", "3.7.1",
    "nbconvert", "7.4.0",
    "nbformat", "5.8.0",
    "notebook", "6.5.4",
    "numpy", "1.24.3",
    "openpyxl", "3.1.2",
    "packaging", "23.1",
    "palettable", "3.3.3",
    "pandas", "2.0.1",
    "pandocfilters", "1.5.0",
    "parso", "0.8.3",
    "patsy", "0.5.3",
    "pexpect", "4.8.0",
    "pickleshare", "0.7.5",
    "plotnine", "0.12.1",
    "prompt-toolkit", "3.0.38",
    "psutil", "5.9.5",
    "ptyprocess", "0.7.0",
    "PuLP", "2.8.0",
    "Pygments", "2.15.1",
    "pyparsing", "3.0.9",
    "python-dateutil", "2.8.2",
    "pytz", "2023.3",
    "PyYAML", "6.0",
    "pyzmq", "25.0.2",
    "ratelimiter", "1.2.0.post0",
    "requests", "2.30.0",
    "rpy2", "3.5.0",
    "scikit-learn", "1.2.2",
    "scipy", "1.10.1",
    "seaborn", "0.12.2",
    "setuptools", "46.3.0",
    "six", "1.16.0",
    "snakemake", "8.11.6",
    "statsmodels", "0.14.0",
    "tornado", "6.3.1",
    "traitlets", "5.9.0",
    "urllib3", "2.0.2",
    "utils", "1.0.1",
    "webencodings", "0.5.1",
    "widgetsnbextension", "4.0.7",
    "wheel", "0.34.2",
    "wrapt", "1.15.0",
    "zipp", "3.15.0"
)

python_libraries
```

### commandline packages
```{r}
cli_tools <- tribble(
~Software,~Version,~Source,
"bedtools","2.28.0","https://github.com/arq5x/bedtools2/",
"bedops","2.4.37","https://github.com/bedops/",
"genometools","1.6.2","http://genometools.org/pub/genometools-1.6.2.tar.gz",
"HTSlib","1.9","https://github.com/samtools/htslib/",
"MCR","R2014a","https://www.mathworks.com/supportfiles/downloads/R2014a/",
"GISTIC2","2.0.23","ftp://ftp.broadinstitute.org/pub/GISTIC2.0/", 
"awscliv2","","https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip",
"Desal","2.1.1","https://github.com/TomWright/dasel/releases/download/v2.1.1/dasel_linux_amd64"
)
cli_tools
```

### combine all together
```{r}
list_package_table <- list(r_packages = r_packages, 
                           python_libraries = python_libraries, 
                           cli_tools = cli_tools)

openxlsx::write.xlsx(list_package_table, "results/SuppTable4-List_Package_Table.xlsx")
```
